version: '3.8'
services:
  app:
    build: .
    ports:
      - "80090:8009"
    env_file:
      - .env  # Carrega o arquivo .env dentro do contêiner
    volumes:
      - .:/app  # Mapeia o diretório local para o contêiner (opcional)
